name: taski
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  flutter_modular: ^6.3.4
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  mobx_codegen: ^2.7.0
  sqflite: ^2.4.1
  path: ^1.9.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/